### ISSUE TITLE
Error in Downloading Packages: Multiple packages link to with SDL2

### ISSUE THREAD

**Issue by pintert3** [Swampsoft/solitaire#9]
Got this error when trying to `cargo run --release`

error: multiple packages link to native library `SDL2`, but a native library can be linked only once

package `sdl2-sys v0.31.0`
    ... which is depended on by `sdl2 v0.31.0`
    ... which is depended on by `gfx_window_sdl v0.8.0`
    ... which is depended on by `ggez v0.4.4`
    ... which is depended on by `solitaire v0.2.0 (/home/pintert3/solitaire-0.2.0)`
links to native library `SDL2`

package `sdl2-sys v0.34.3`
    ... which is depended on by `sdl2 v0.34.3`
    ... which is depended on by `solitaire v0.2.0 (/home/pintert3/solitaire-0.2.0)`
also links to native library `SDL2`

**Comment by mbillingr** [comment]
Thank you for reporting this issue!

It will take me a few days to look into this.

Meanwhile, can you let me know which version of Cargo you are using?

**Comment by mbillingr** [comment]
This should be fixed by updating to ggez 5.0, which no longer depends on SDL.

Could you please try if the `ggez-5` branch works for you?

**Comment by pintert3** [comment]
That fixed it. It now works fine, thanks!
And just in case it matters, I'm using `cargo 1.46.0`

**Comment by mbillingr** [comment]
Perfect. Thank you for the help!
